base:
  # mysql
  mysql:
    ipAddr: 192.168.10.10
    port: 3306
    username: root
    password: Wiselink4100!
    hikari:
      # 池中维护的最小空闲连接数
      minimum-idle: 5
      # 池中最大连接数，包括闲置和使用中的连接
      maximum-pool-size: 10
      # 自动提交从池中返回的连接
      auto-commit: true
      # 连接允许在池中闲置的最长时间
      idle-timeout: 30000
      # 池中连接最长生命周期
      max-lifetime: 1800000
      # 等待来自池的连接的最大毫秒数
      connection-timeout: 30000
  # redis
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 192.168.10.10
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 
    # 连接超时时间（毫秒）
    timeout: 5000
    # lettuce 基于 netty 实现的连接池，是线程安全的
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 20
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 5
      # 连接池中的最小空闲连接
      min-idle: 0
  # mongoDB
  mongoDB:
    host: 192.168.10.10
    port: 27017
    username: fql
    password: qwe123




